### ISSUE TITLE
Sandbox for Sensu 2.x

### ISSUE THREAD

**Issue by obfuscurity** [sensu/sandbox#20]

**Comment by jspaleta** [comment]
Merging in initial Sensu 2 vagrantfile today.

Initial "pipeline" lesson plan is blocked on Sensu 2 api documentation becoming available.

Pointing to Sensu 2 getting started docs for now in the sandbox readme.

**Comment by obfuscurity** [comment]
@jspaleta Anything I can do to help move this along?
