### ISSUE TITLE
Enterprise sandbox installs outdated version of Sensu Core

### ISSUE THREAD

**Issue by apaskulin** [sensu/sandbox#27]
Seeing Sensu Core version 1.4 instead of 1.5 when spinning up the Enterprise sandbox

**Comment by jspaleta** [comment]
The provisioning should be installing the latest official packages when creating a brand new virtual machine. There is nothing specific in the provisioning. I'm not sure why you are getting version 1.4 if 1.5 is the most recently available packages. 

I just built a fresh enterprise virtual machine and I have installed:

sensu-enterprise-3.1.0-1.noarch
sensu-1.5.0-1.el7.x86_64
sensu-enterprise-dashboard-2.12.0-1.x86_64

**Comment by apaskulin** [comment]
Interesting. I thought this might be the result of not adding the Sensu Core YUM repository during provisioning, but if you're unable to reproduce, feel free to close this.
