### ISSUE TITLE
View logs for handlers

### ISSUE THREAD

**Issue by dineshraj01** [sensu/sandbox#45]
Hi,
How do I view logs for sensu handlers. I created one handler for integration with opsgenie. Its visible with 'sensuctl handler list', but not working with the checks. How can I check whats wrong with my handler??

**Comment by dineshraj01** [comment]
I am using sensu go sandbox.

**Comment by asachs01** [comment]
@dineshraj01 hi! :wave: For this sort of thing, I'd highly recommend jumping into either our community slack (slack.sensu.io) or hopping on our Discourse site: discourse.sensu.io. It's worth noting that Sensu Go uses journald for all logging, so doing something like `journalctl -u sensu-backend` should get you log output. If you're still not able to identify the issue, please join the #sensu-go channel in our slack. We've got plenty of folks available there to help.

**Comment by dineshraj01** [comment]
Thanks for the quick response :) I'll post my queries in slack.
