### ISSUE TITLE
Grafana Dashboard Login Failure 

### ISSUE THREAD

**Issue by arky** [sensu/sandbox#70]
It is not possible to login to Grafana Dashboard in the sandbox. The Grafana Sign-In URI is always pointing to port 4000. 

http://localhost:4000/?orgId=1&forceLogin=true

**Comment by jspaleta** [comment]
Inside the vagrant virtual machine, grafana is using port 4000
But the vagrant configuration maps this to port 4002 on the host computer when ENABLE_SENSU_SANDBOX_PORT_FORWARDING is set

Unfortunately there's no garuntee that 4002 on the virtual machine host will be available.  You may need to adjust the Vagrantfile to choose a free port that works.
